# @package _global_

defaults:
  - terrain_base

terrain:
  mesh_type: trimesh
  curriculum: true
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.0
  measure_heights: false
  horizontal_scale: 0.05
  vertical_scale: 0.005
  border_size: 0.0
  max_init_terrain_level: 0
  terrain_length: 3.0
  terrain_width: 3.0
  num_rows: 1
  num_cols: 1
  terrain_types: [external_obj_box]
  terrain_proportions: [1.0]
  external_stl_files:
    external_obj_box: dataset/limb_20_z_scale_1.0_piplus_mapping/terrain_mjlab.obj
  slope_treshold: 0.75
